### ISSUE TITLE
hello,I can't get  last insert id  use  id() method,id method return is null 

### ISSUE THREAD

**Issue by mgckid** [voku/idiorm#2]
#开启事务
        $this->beginTransaction();
        #创建文章主记录
        $this->orm()->create($data)->save();
        $articleId = $this->orm()->id();
        if (!$articleId) {
            $this->rollBack(); #事务回滚
            $this->setMessage('文章主记录添加失败');
            return FALSE;
        }
I var_dump in orm code find the insert operation is   success ,but when I use id method to get last insert id ,the id lost; I feel uncertain 。is there has something wrong with my code ?

**Comment by voku** [comment]
Hi, I have added some tests for MySQL, so you can see how it is should work. (tested with PHP 5.3 .. PHP 7 via Travis-CI)

https://github.com/voku/idiorm/commit/909995ce2a65db0a84c90e8070a95dbee1378e46#diff-6f6a4622da44f62ee4927eff859d85d0R61

**Comment by mgckid** [comment]
^_^ ,   I  check your test code and compare with mine ,than I find wrong usage in  my code ，

// I save like this
$this->orm()->create($data)->save();

//after save I get id like this 
$articleId = $this->orm()->id();

there  has two instance of table model , data in different instance  is not shared; so I can't get the id;

//right usage should be like:
$obj = $this->orm()
$obj->create($data)->save();
$obj->id();

thank you for your help.  and thanks for maintain the idiorm, I like this orm  project,it is simple and effect. I use it in my website .

**Comment by voku** [comment]
:) good to know that you cold solve your problem, I will close the issue ...
